force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Universal Containers Lawyers&apos; Customers</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Firms that provide legal services to different clients.</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Nombre de Legal Advisor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    public static void createTestRecords(Integer numLegalAdvisors, Integer numClientsPerAdvisor) {
        List<Legal_Advisor__c> legalAdvisors = new List<Legal_Advisor__c>();
        
        for(Integer i=0;i<numLegalAdvisors;i++) {
            Legal_Advisor__c a = new Legal_Advisor__c(Name='TestAccount' + i);
            legalAdvisors.add(a);
        }
        insert legalAdvisors;
        
        List<Client__c> clients = new List<Client__c>();
        for (Integer j=0;j<numLegalADvisors;j++) {
            Legal_Advisor__c legalAdvisor = legalAdvisors[j];            
            // For each account just inserted, add contacts
            for (Integer k=numClientsPerAdvisor*j;k<numClientsPerAdvisor*(j+1);k++) {
                clients.add(new Client__c(First_Name__c='Test',
                                     Last_Name__c='Test',
                                     Legal_Advisor__c=legalAdvisor.Id));
            }
        }
        // Insert all clients for all legal advisors
        insert clients;
    }
}