force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <description>Universal Containers Lawyers&apos; Customers</description>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <label>Client Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Error Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <description>Firms that provide legal services to different clients.</description>
    <label>Legal Advisor</label>
    <nameField>
        <label>Nombre de Legal Advisor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_NightlyServiceTest.cls
@isTest
private class ucl_NightlyServiceTest {
    @isTest
    static void testProcessData() {
        Test.setMock(HttpCalloutMock.class, new ucl_NightlyServiceMock());
        ucl_NightlyService.processData();

       	List<Legal_Advisor__c> enabledLegalAdvisors = [SELECT Account_Number__c, Account_Status__c FROM Legal_Advisor__c WHERE Account_Status__c = 'Enabled'];
        List<Legal_Advisor__c> legalAdvisor = [SELECT Account_Name__c, Account_Number__c FROM Legal_Advisor__c WHERE Account_Number__c = '9afccdd3-e7c4-4789-a465-1734886633d2'];
        System.assertEquals(1, legalAdvisor.size());
        System.assertEquals('Centidel', legalAdvisor[0].Account_Name__c);
        System.assertEquals(true, ucl_NightlyService.isLegalAdvisorEnabled(enabledLegalAdvisors, legalAdvisor[0].Account_Number__c));

    }
    @isTest
    static void testExistingData(){
       // Set up test data
       Legal_Advisor__c existingLegalAdvisor = new Legal_Advisor__c(
            Account_Number__c = '123',
            Account_Status__c = 'Enabled'
        );
        insert existingLegalAdvisor;
        Test.startTest();
       	Test.setMock(HttpCalloutMock.class, new ucl_NightlyServiceMock());  
        ucl_NightlyService.processData();
        Test.stopTest();
        List<Legal_Advisor__c> updatedLegalAdvisor = [SELECT Account_Number__c, Account_Status__c FROM Legal_Advisor__c WHERE Account_Number__c = '123'];
        List<Legal_Advisor__c> enabledLegalAdvisors = [SELECT Account_Number__c, Account_Status__c FROM Legal_Advisor__c WHERE Account_Status__c = 'Enabled'];

        System.assertEquals(1, updatedLegalAdvisor.size());
        System.assertEquals('Disabled', updatedLegalAdvisor[0].Account_Status__c);
        System.assertEquals(false, ucl_NightlyService.isLegalAdvisorEnabled(enabledLegalAdvisors, updatedLegalAdvisor[0].Account_Number__c));
    }

    @isTest
	static void testDeletingClients(){
       // Set up test data
       	ucl_TestDataFactory.createTestRecords(1, 2);
        Test.startTest();
       	Test.setMock(HttpCalloutMock.class, new ucl_NightlyServiceMock());  
        ucl_NightlyService.processData();
        Test.stopTest();
        List<Client__c> oldClient = [SELECT Client_Number__c FROM Client__c WHERE First_Name__c = 'Test'];

        System.assertEquals(0, oldClient.size());
    } 
    
    @isTest
    static void testErrorHandling(){
        // Mock an exception that might occur during processing
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ucl_ErrorMock());
        ucl_NightlyService.processData();
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
		
        // Validate that the error has been logged
        List<Error_Log__c> errorLogs = [SELECT Name FROM Error_Log__c];
        System.assertNotEquals(0, errorLogs.size());
        // Validate that an email has been sent
        system.assertEquals(1, invocations, 'An email should be sent');
        
    }
  
}